// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace PortalApiGusApiRegonData.Models
{
    [Table("dbo.PortalApiGusApiRegonData")]
    public partial class PortalApiGusApiRegonData
    {
        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength(128)]
        public string Name { get; set; }
        [Required]
        public string Description { get; set; }
        [Column(TypeName = "money")]
        public decimal? PricePerClick { get; set; }
        public int? NumberOfClicks { get; set; }
        [Column(TypeName = "money")]
        public decimal? TotalCost { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? Created { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? Modified { get; set; }
    }
}