// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace PortalApiGusApiRegonData.Models
{
    public partial class PortalApiGusApiRegonDataContext : DbContext
    {
        public virtual DbSet<PortalApiGusApiRegonData> PortalApiGusApiRegonData { get; set; }
        public virtual DbSet<PortalApiGusApiRegonDataAudit> PortalApiGusApiRegonDataAudit { get; set; }

        public PortalApiGusApiRegonDataContext(DbContextOptions<PortalApiGusApiRegonDataContext> options) : base(options)
        {
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<PortalApiGusApiRegonData>(entity =>
            {
                entity.Property(e => e.Created).HasDefaultValueSql("(getdate())");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}