// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PortalApiGusApiRegonData.Data;

namespace PortalApiGusApiRegonData.Migrations
{
    [DbContext(typeof(PortalApiGusApiRegonDataDbContext))]
    partial class PortalApiGusApiRegonDataDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PortalApiGusApiRegonData.Models.DaneSzukajPodmioty.DaneSzukajPodmioty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<DateTime?>("DataModyfikacji")
                        .HasColumnName("DataModyfikacji")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("DataUtworzenia")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnName("DataUtworzenia")
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("DataZakonczeniaDzialalnosci")
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<string>("Gmina")
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<string>("KodPocztowy")
                        .HasColumnType("nvarchar(12)")
                        .HasMaxLength(12);

                    b.Property<string>("Miejscowosc")
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<string>("MiejscowoscPoczty")
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<string>("Nazwa")
                        .HasColumnType("nvarchar(2000)")
                        .HasMaxLength(2000);

                    b.Property<string>("Nip")
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<string>("NrLokalu")
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<string>("NrNieruchomosci")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("ParametryWyszukiwaniaJson")
                        .HasColumnType("nvarchar(max)")
                        .HasMaxLength(2147483647);

                    b.Property<string>("ParametryWyszukiwaniaSHA512")
                        .HasColumnType("nvarchar(max)")
                        .HasMaxLength(2147483647);

                    b.Property<string>("Powiat")
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<string>("Regon")
                        .HasColumnType("nvarchar(14)")
                        .HasMaxLength(14);

                    b.Property<int?>("SilosID")
                        .HasColumnType("int");

                    b.Property<string>("StatusNip")
                        .HasColumnType("nvarchar(12)")
                        .HasMaxLength(12);

                    b.Property<string>("Typ")
                        .HasColumnType("nvarchar(2)")
                        .HasMaxLength(2);

                    b.Property<string>("Ulica")
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<string>("UniqueIdentifierOfTheLoggedInUser")
                        .HasColumnName("UniqueIdentifierOfTheLoggedInUser")
                        .HasColumnType("varchar(512)")
                        .HasMaxLength(512);

                    b.Property<string>("Wojewodztwo")
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.HasKey("Id");

                    b.HasIndex("Gmina")
                        .HasName("IX_DaneSzukajPodmiotyGmina");

                    b.HasIndex("Id")
                        .IsUnique()
                        .HasName("IX_DaneSzukajPodmiotyId");

                    b.HasIndex("KodPocztowy")
                        .HasName("IX_DaneSzukajPodmiotyKodPocztowy");

                    b.HasIndex("Miejscowosc")
                        .HasName("IX_DaneSzukajPodmiotyMiejscowosc");

                    b.HasIndex("MiejscowoscPoczty")
                        .HasName("IX_DaneSzukajPodmiotySilosMiejscowoscPoczty");

                    b.HasIndex("Nazwa")
                        .HasName("IX_DaneSzukajPodmiotyNazwa");

                    b.HasIndex("Nip")
                        .HasName("IX_DaneSzukajPodmiotyNip");

                    b.HasIndex("Powiat")
                        .HasName("IX_DaneSzukajPodmiotyPowiat");

                    b.HasIndex("Regon")
                        .HasName("IX_DaneSzukajPodmiotyRegon");

                    b.HasIndex("SilosID")
                        .HasName("IX_DaneSzukajPodmiotySilosID");

                    b.HasIndex("Typ")
                        .HasName("IX_DaneSzukajPodmiotyTyp");

                    b.HasIndex("Ulica")
                        .HasName("IX_DaneSzukajPodmiotyUlica");

                    b.HasIndex("UniqueIdentifierOfTheLoggedInUser")
                        .HasName("IX_DaneSzukajPodmiotyUniqueIdentifierOfTheLoggedInUser");

                    b.HasIndex("Wojewodztwo")
                        .HasName("IX_DaneSzukajPodmiotyWojewodztwo");

                    b.ToTable("DaneSzukajPodmioty","pagard");
                });

            modelBuilder.Entity("PortalApiGusApiRegonData.Models.DaneSzukajPodmioty.DaneSzukajPodmiotyParametryWyszukiwania", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("(newsequentialid())");

                    b.Property<DateTime?>("DataModyfikacji")
                        .HasColumnName("DataModyfikacji")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("DataUtworzenia")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnName("DataUtworzenia")
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Krs")
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<string>("Krsy")
                        .HasColumnType("nvarchar(220)")
                        .HasMaxLength(220);

                    b.Property<string>("Nip")
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<string>("Nipy")
                        .HasColumnType("nvarchar(220)")
                        .HasMaxLength(220);

                    b.Property<string>("Regon")
                        .HasColumnType("nvarchar(14)")
                        .HasMaxLength(14);

                    b.Property<string>("Regony14zn")
                        .HasColumnType("nvarchar(300)")
                        .HasMaxLength(300);

                    b.Property<string>("Regony9zn")
                        .HasColumnType("nvarchar(200)")
                        .HasMaxLength(200);

                    b.Property<string>("SHA512")
                        .HasColumnType("nvarchar(max)")
                        .HasMaxLength(2147483647);

                    b.Property<string>("UniqueIdentifierOfTheLoggedInUser")
                        .HasColumnName("UniqueIdentifierOfTheLoggedInUser")
                        .HasColumnType("varchar(512)")
                        .HasMaxLength(512);

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique()
                        .HasName("IX_DaneSzukajPodmiotyParametryWyszukiwaniaId");

                    b.HasIndex("Krs")
                        .HasName("IX_DaneSzukajPodmiotyParametryWyszukiwaniaKrs");

                    b.HasIndex("Krsy")
                        .HasName("IX_DaneSzukajPodmiotyParametryWyszukiwaniaKrsy");

                    b.HasIndex("Nip")
                        .HasName("IX_DaneSzukajPodmiotyParametryWyszukiwaniaNip");

                    b.HasIndex("Nipy")
                        .HasName("IX_DaneSzukajPodmiotyParametryWyszukiwaniaNipy");

                    b.HasIndex("Regon")
                        .HasName("IX_DaneSzukajPodmiotyParametryWyszukiwaniaRegon");

                    b.HasIndex("Regony14zn")
                        .HasName("IX_DaneSzukajPodmiotyParametryWyszukiwaniaRegony14zn");

                    b.HasIndex("Regony9zn")
                        .HasName("IX_DaneSzukajPodmiotyParametryWyszukiwaniaRegony9zn");

                    b.HasIndex("UniqueIdentifierOfTheLoggedInUser")
                        .HasName("IX_DaneSzukajPodmiotyParametryWyszukiwaniaUniqueIdentifierOfTheLoggedInUser");

                    b.ToTable("DaneSzukajPodmiotyParametryWyszukiwania","pagard");
                });
#pragma warning restore 612, 618
        }
    }
}
